/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "atnotdmrkjacqrbjpkbn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bm90ZG1ya2phY3FyYmpwa2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE3MTA5ODUsImV4cCI6MjA5NzI4Njk4NX0.twIMJNiyMy1QI6ZfbqiPK-6kBvWN6y4MkNV2-jQ2hVs"